// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "SmartDashboard/SmartDashboard.h"
#include "Motors.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Motors::Motors() : Subsystem("Motors") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    encoder2 = RobotMap::motorsencoder2;
    encoder1 = RobotMap::motorsencoder1;
    limitSwitch2 = RobotMap::motorslimitSwitch2;
    limitSwitch1 = RobotMap::motorslimitSwitch1;
    cANTalon2 = RobotMap::motorsCANTalon2;
    cANTalon1 = RobotMap::motorsCANTalon1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
void Motors::setMotors(float amt)
{
	cANTalon1->Set(amt);
	cANTalon2->Set(amt);
	SmartDashboard::PutNumber("Encoder 1 Position", cANTalon1->GetEncPosition());
	SmartDashboard::PutNumber("Encoder 2 Position", cANTalon2->GetEncPosition());
}
void Motors::ResetEncoders()
{
	cANTalon1->SetEncPosition(0);
	cANTalon2->SetEncPosition(0);
}
void Motors::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

